"""
model/train_clip_probe.py

Train a logistic regression probe on frozen CLIP image embeddings.
Labels come from data/labels/image_labels.csv (generated by the Label tab).

Usage:
    python model/train_clip_probe.py
    python model/train_clip_probe.py --dry-run   # first 20 labeled images only
"""

import argparse
import io
import os
from pathlib import Path

import boto3
import joblib
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from dotenv import load_dotenv
from PIL import Image
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from tqdm import tqdm
from transformers import CLIPModel, CLIPProcessor

# ── env ───────────────────────────────────────────────────────────────────────
load_dotenv(dotenv_path=Path(__file__).parents[1] / ".env", override=True)

BUCKET        = os.getenv("S3_BUCKET_NAME", "street-risk-mvp")
REGION        = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
MODEL_NAME    = "openai/clip-vit-base-patch32"

LABELS_CSV    = Path(__file__).parents[1] / "data" / "labels" / "image_labels.csv"
PROBE_PATH    = Path(__file__).parent / "clip_probe.pkl"


# ── public API (imported by tests) ───────────────────────────────────────────

def train_probe(embeddings: np.ndarray, labels: np.ndarray) -> LogisticRegression:
    """
    Fit a logistic regression on CLIP embeddings.
    embeddings: (N, 512) float32
    labels:     (N,)    int  — 1=high risk, 0=low risk
    Raises ValueError if only one class is present.
    """
    unique = np.unique(labels)
    if len(unique) < 2:
        raise ValueError("Training requires at least two classes (high and low risk).")
    probe = LogisticRegression(max_iter=1000, C=1.0, random_state=42)
    probe.fit(embeddings, labels)
    return probe


def aggregate_to_hex(df: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate per-image clip_risk_prob to per-hex mean.
    df must have columns: h3_index, clip_risk_prob
    Returns DataFrame with columns: h3_index, clip_risk_prob
    """
    return (
        df.groupby("h3_index")["clip_risk_prob"]
          .mean()
          .reset_index()
    )


# ── helpers ───────────────────────────────────────────────────────────────────

def make_s3():
    kwargs: dict = {"region_name": REGION}
    if os.getenv("AWS_ACCESS_KEY_ID"):
        kwargs["aws_access_key_id"] = os.getenv("AWS_ACCESS_KEY_ID")
        kwargs["aws_secret_access_key"] = os.getenv("AWS_SECRET_ACCESS_KEY")
    return boto3.client("s3", **kwargs)


def download_image(s3, key: str) -> Image.Image:
    buf = io.BytesIO()
    s3.download_fileobj(BUCKET, key, buf)
    buf.seek(0)
    return Image.open(buf).convert("RGB")


def load_clip(device: str):
    print(f"  Loading {MODEL_NAME} on {device} ...")
    model     = CLIPModel.from_pretrained(MODEL_NAME).to(device)
    processor = CLIPProcessor.from_pretrained(MODEL_NAME)
    model.eval()
    return model, processor


def extract_embedding(image: Image.Image, model, processor, device: str) -> np.ndarray:
    """Extract a single 512-dim L2-normalised CLIP image embedding."""
    inputs = processor(images=[image], return_tensors="pt").to(device)
    with torch.no_grad():
        emb = model.get_image_features(**inputs)
    emb = F.normalize(emb, dim=-1)
    return emb.cpu().numpy()[0]   # (512,)


# ── main ──────────────────────────────────────────────────────────────────────

def main(dry_run: bool = False):
    print("\n- CLIP probe training -\n")

    # 1. Load labels
    print("Step 1/4  Loading labels ...")
    if not LABELS_CSV.exists():
        raise FileNotFoundError(
            f"Labels file not found: {LABELS_CSV}\n"
            "Run the Streamlit app locally and label images first."
        )
    labels_df = pd.read_csv(LABELS_CSV)
    labels_df = labels_df[labels_df["label"].isin(["high", "low"])].reset_index(drop=True)
    print(f"  [ok] {len(labels_df)} labeled images  (high={( labels_df['label']=='high').sum()}, low={(labels_df['label']=='low').sum()})")

    if dry_run:
        labels_df = labels_df.head(20)
        print(f"  (--dry-run) Limited to {len(labels_df)} images")

    y = (labels_df["label"] == "high").astype(int).values

    # 2. Load CLIP + S3
    print("\nStep 2/4  Loading CLIP model and S3 client ...")
    device = "cpu"
    model, processor = load_clip(device)
    s3 = make_s3()

    # 3. Extract embeddings for labeled images
    print(f"\nStep 3/4  Extracting embeddings for {len(labels_df)} labeled images ...")
    embeddings = []
    valid_idx  = []

    for i, row in tqdm(labels_df.iterrows(), total=len(labels_df), desc="Embedding"):
        try:
            img = download_image(s3, row["s3_key"])
            emb = extract_embedding(img, model, processor, device)
            embeddings.append(emb)
            valid_idx.append(i)
        except Exception as e:
            tqdm.write(f"  [warn] Skipping {row['s3_key']}: {e}")

    if not embeddings:
        raise RuntimeError(
            "No embeddings extracted — all image downloads failed. "
            "Check S3 credentials and bucket name."
        )
    embeddings = np.stack(embeddings)   # (N, 512)
    y_valid    = y[valid_idx]
    print(f"  [ok] {len(embeddings)} embeddings extracted")

    # 4. Train probe + 5-fold CV
    print("\nStep 4/4  Training logistic regression probe ...")
    probe  = train_probe(embeddings, y_valid)
    n_folds = max(2, min(5, len(embeddings) // 2))
    cv_acc = cross_val_score(probe, embeddings, y_valid, cv=n_folds, scoring="accuracy")
    print(f"  [ok] 5-fold CV accuracy: {cv_acc.mean():.3f} ± {cv_acc.std():.3f}")

    # Save
    joblib.dump(probe, PROBE_PATH)
    print(f"  [ok] Probe saved: {PROBE_PATH}")

    print("\n- Done. Run extract_clip_features.py --use-probe to score all images. -\n")
    return probe


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train CLIP linear probe.")
    parser.add_argument("--dry-run", action="store_true", help="Use first 20 labeled images only.")
    args = parser.parse_args()
    main(dry_run=args.dry_run)
